export const SAMPLE_MENU_DATA = [
  {
    id: '1',
    name: 'Margherita Pizza',
    description: 'Classic Italian pizza with fresh tomatoes, mozzarella, and basil',
    price: 299,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500',
    available: true,
    badge: 'Bestseller',
  },
  {
    id: '2',
    name: 'Chicken Burger',
    description: 'Juicy grilled chicken patty with fresh lettuce, tomatoes, and special sauce',
    price: 199,
    category: 'Fast Food',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
    available: true,
  },
  {
    id: '3',
    name: 'Chicken Biryani',
    description: 'Aromatic basmati rice cooked with tender chicken and special spices',
    price: 249,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500',
    available: true,
    badge: 'Popular',
  },
  {
    id: '4',
    name: 'Caesar Salad',
    description: 'Fresh romaine lettuce with parmesan cheese, croutons, and Caesar dressing',
    price: 179,
    category: 'Salads',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500',
    available: true,
  },
  {
    id: '5',
    name: 'Pasta Alfredo',
    description: 'Creamy fettuccine pasta with parmesan and garlic',
    price: 229,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500',
    available: true,
  },
  {
    id: '6',
    name: 'Chocolate Brownie',
    description: 'Rich chocolate brownie with vanilla ice cream',
    price: 129,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500',
    available: true,
  },
  {
    id: '7',
    name: 'Fresh Lemonade',
    description: 'Freshly squeezed lemon juice with mint',
    price: 79,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f0f?w=500',
    available: true,
  },
  {
    id: '8',
    name: 'Paneer Tikka',
    description: 'Grilled cottage cheese marinated in Indian spices',
    price: 199,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500',
    available: true,
  },
  {
    id: '9',
    name: 'French Fries',
    description: 'Crispy golden fries with ketchup and mayo',
    price: 99,
    category: 'Fast Food',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500',
    available: true,
  },
  {
    id: '10',
    name: 'Veg Fried Rice',
    description: 'Stir-fried rice with mixed vegetables and soy sauce',
    price: 159,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500',
    available: true,
  },
  {
    id: '11',
    name: 'Garlic Bread',
    description: 'Toasted bread with garlic butter and herbs',
    price: 99,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1573140401552-388e5ae4f3f2?w=500',
    available: true,
  },
  {
    id: '12',
    name: 'Mango Smoothie',
    description: 'Creamy mango smoothie with fresh fruits',
    price: 119,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=500',
    available: true,
  },
  {
    id: '13',
    name: 'Veggie Pizza',
    description: 'Loaded with bell peppers, olives, mushrooms, and cheese',
    price: 279,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96586?w=500',
    available: false,
  },
  {
    id: '14',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with coffee and mascarpone',
    price: 159,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500',
    available: true,
  },
  {
    id: '15',
    name: 'Chicken Wings',
    description: 'Spicy buffalo wings with ranch dipping sauce',
    price: 249,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=500',
    available: true,
  },
];

export default SAMPLE_MENU_DATA;
